services:
  opal:
    image: obiba/opal:4.4
#    build: opal
    ports:
      - "8870:8080"
    depends_on:
      - mongo
      - rock
    environment:
      - OPAL_ADMINISTRATOR_PASSWORD=password
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - ROCK_HOSTS=rock:8085
    volumes:
      - C:\Users\Tomasoni\git\VisualSHIELD\opal\conf:/srv/conf

  rock:
    #image: datashield/rock-base:latest
    build: rock-visualshield
    ports:
      - 8085:8085
    environment:
      - ROCK_ID=default-1
      - ROCK_CLUSTER=default

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      
  mongo:
    image: mongo:4.2
    command: --serviceExecutor adaptive --wiredTigerCacheSizeGB 2
    deploy:
      resources:
        limits:
          memory: 6gb
        reservations:
          memory: 4gb
    volumes:
      - mongodata:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongodata:    # does not need anything underneath this