version: "3.1"
services:
  opal:
    image: obiba/opal:4.4
    ports:
      - "8870:8080"
      - "8843:8443"
    depends_on:
      - mongo
      - rock
    environment:
      - OPAL_ADMINISTRATOR_PASSWORD=password
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - ROCK_HOSTS=rock:8085
    #volumes:
    #  - ./opal/conf:/srv/conf

  rock:
    image: cosbi/rock-visualshield:1.0.0
    ports:
      - 8085:8085
    environment:
      - ROCK_ID=default-1
      - ROCK_CLUSTER=default
    volumes:
      - ./rock/conf:/srv/conf
      
  mongo:
    image: mongo:4.2
    command: --serviceExecutor adaptive --wiredTigerCacheSizeGB 2
    deploy:
      resources:
        limits:
          memory: 6gb
        reservations:
          memory: 4gb
    volumes:
      - mongodata:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongodata:    # does not need anything underneath this
